# Generated by Django 3.2.6 on 2021-08-31 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snacks', '0002_snack_descreption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='descreption',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='name',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='snack',
            name='purchaser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snack',
            name='title',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
    ]
